#Then, run the commands to build and run the Docker image:
#$ docker build -t image_apache2 .
#$ docker run -dit --rm --name container_apache2 -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ image_apache2


FROM httpd:2.4
#COPY ./ /usr/local/apache2/htdocs/


